
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kentj
 */
public class Directors extends javax.swing.JFrame {

    ArrayList<addclass> jadd;
    String header[] = new String[]{"Name of Director", "Direct Movie", "Role"};
    DefaultTableModel table;
    int row, column;

    public Directors() {
        initComponents();
         jadd = new ArrayList<>();
        table = new DefaultTableModel(header, 0);
        jTable1.setModel(table);
        this.setLocationRelativeTo(null);
        Seticon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDirectname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDirectrole = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDirectmovie = new javax.swing.JTextField();
        btnDELETE = new javax.swing.JButton();
        btnADD = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon("C:\\Users\\kentj\\Downloads\\back-arrow-removebg-preview.png")); // NOI18N
        back.setText("Back to Menu");
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 210, 40));

        jLabel2.setBackground(new java.awt.Color(0, 0, 102));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 60));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INSERT DIRECTOR'S NAME");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));
        jPanel1.add(txtDirectname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 280, 30));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("INSERT DIRECTOR'S MOVIE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        txtDirectrole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirectroleActionPerformed(evt);
            }
        });
        jPanel1.add(txtDirectrole, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 280, 30));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("INSERT DIRECTOR'S ROLE IN THE MOVIE  ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, 40));

        txtDirectmovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirectmovieActionPerformed(evt);
            }
        });
        jPanel1.add(txtDirectmovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 280, 30));

        btnDELETE.setBackground(new java.awt.Color(0, 0, 0));
        btnDELETE.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnDELETE.setForeground(new java.awt.Color(255, 255, 255));
        btnDELETE.setText("DELETE");
        btnDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETEActionPerformed(evt);
            }
        });
        jPanel1.add(btnDELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 590, 120, 50));

        btnADD.setBackground(new java.awt.Color(0, 0, 0));
        btnADD.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnADD.setForeground(new java.awt.Color(255, 255, 255));
        btnADD.setText("ADD");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });
        jPanel1.add(btnADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 120, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name of Director", "Directed Movie", "Role "
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 740, 570));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\kentj\\Downloads\\BAGONG KS STUDIO BKG 2.png")); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1200, 790));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void Seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ks-studio-icon.png")));
    }
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:

        menu men=new menu();

        men.show();

        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void txtDirectroleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirectroleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirectroleActionPerformed

    private void txtDirectmovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirectmovieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirectmovieActionPerformed

    private void btnDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETEActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
        tblModel.removeRow(jTable1.getSelectedRow());
        //delete row
        if(jTable1.getSelectedRowCount()==1){
            tblModel.removeRow(jTable1.getSelectedRow());
        }else{
            if(jTable1.getRowCount()==0){
                //mu pop up kung empty
                JOptionPane.showMessageDialog(this, "Table is Empty.");
            }else{
                //mu pop up kung walay i delete n row 
                JOptionPane.showMessageDialog(this, "Please Select One Row");
            }
        }
    }//GEN-LAST:event_btnDELETEActionPerformed

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
        // TODO add your handling code here:
        String jtitle = txtDirectname.getText();
        String jgenre = txtDirectmovie.getText();
        String jdatereleased = txtDirectrole.getText();

        txtDirectname.setText(jtitle);
        txtDirectmovie.setText(jgenre);
        txtDirectrole.setText(jdatereleased);
        jadd.add(new addclass(jtitle, jgenre, jdatereleased));
        table.setRowCount(0);

        for (int i = 0; i < jadd.size(); i++) {
            Object[] objs = {jadd.get(i).jtitle, jadd.get(i).jgenre, jadd.get(i).jdatereleased, jadd.get(i)};
            table.addRow(objs);

        }
       
    }//GEN-LAST:event_btnADDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Directors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Directors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Directors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Directors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Directors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnDELETE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDirectmovie;
    private javax.swing.JTextField txtDirectname;
    private javax.swing.JTextField txtDirectrole;
    // End of variables declaration//GEN-END:variables
}
